# Usar la imagen de PHP con Apache preconfigurado
FROM php:8.2-apache

# Copiar el archivo index.php desde src al directorio raíz de Apache
COPY . /var/www/html/

# Exponer el puerto 80 del contenedor
EXPOSE 80
