name: Backend CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up PHP with Composer
        uses: shivammathur/setup-php@v2 
        with:
          php-version: '8.2'
          tools: composer

      - name: Install dependencies
        run: |
          composer install --working-dir=./src/backend

      - name: Run PHPLint
        run: |
          composer global require overtrue/phplint
          ~/.composer/vendor/bin/phplint ./src/backend

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Start backend container
        run: |
          docker-compose -f ./docker-compose.yml up -d backend
          sleep 10

      - name: Run PHPUnit tests
        run: |
          wget https://phar.phpunit.de/phpunit.phar
          chmod +x phpunit.phar
          ./phpunit.phar ./src/backend/indexTest.php

  docker-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CD_TOKEN }}

      - name: Build and Push Backend Image to GHCR
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./src/backend
          file: ./src/backend/Dockerfile
          tags: ghcr.io/peereiraa/calculadora_docker:backend-latest

      - name: Build and Push Frontend Image to GHCR
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./src/frontend
          file: ./src/frontend/Dockerfile
          tags: ghcr.io/peereiraa/calculadora_docker:frontend-latest

  build-and-push-to-dockerhub:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Backend Image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./src/backend
          file: ./src/backend/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/calculadora_action:backend-latest

      - name: Build and Push Frontend Image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./src/frontend
          file: ./src/frontend/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/calculadora_action:frontend-latest
